export var gridData = [{
	"productName": "asdjkh",
	"productCat": "asdf",
	"price": 1234,
	"model": 2008,
	"weight": 123,
	"daysToExpire": 230,
	"popularity": "high"
}, {
		"productName": "vbnv",
		"productCat": "cxzc",
		"price": 332,
		"model": 2009,
		"weight": 124,
		"daysToExpire": 231,
		"popularity": "low"
	}, {
		"productName": "gvv",
		"productCat": "asjd",
		"price": 45,
		"model": 2010,
		"weight": 125,
		"daysToExpire": 232,
		"popularity": "high"
	}, {
		"productName": "uyuguf",
		"productCat": "adssd",
		"price": 341,
		"model": 2011,
		"weight": 126,
		"daysToExpire": 233,
		"popularity": "high"
	}, {
		"productName": "qewse",
		"productCat": "hjg",
		"price": 3424342,
		"model": 2012,
		"weight": 127,
		"daysToExpire": 234,
		"popularity": "high"
	}, {
		"productName": "nmbh",
		"productCat": "dfggf",
		"price": 1239,
		"model": 2013,
		"weight": 128,
		"daysToExpire": 235,
		"popularity": "high"
	}, {
		"productName": "wawk",
		"productCat": "bhbj",
		"price": 768,
		"model": 2014,
		"weight": 129,
		"daysToExpire": 236,
		"popularity": "mid"
	}, {
		"productName": "mkkh",
		"productCat": "nnn",
		"price": 9089,
		"model": 2015,
		"weight": 130,
		"daysToExpire": 237,
		"popularity": "high"
	}, {
		"productName": "zxf",
		"productCat": "nnn",
		"price": 1242,
		"model": 2016,
		"weight": 131,
		"daysToExpire": 238,
		"popularity": "high"
	}, {
		"productName": "thfdg",
		"productCat": "jj",
		"price": 1243,
		"model": 2017,
		"weight": 132,
		"daysToExpire": 239,
		"popularity": "mid"
	}, {
		"productName": "knkn",
		"productCat": "jj",
		"price": 1244,
		"model": 2018,
		"weight": 133,
		"daysToExpire": 240,
		"popularity": "high"
	}, {
		"productName": "njj",
		"productCat": "jj",
		"price": 1245,
		"model": 2019,
		"weight": 134,
		"daysToExpire": 241,
		"popularity": "high"
	}, {
		"productName": "bjhjhb",
		"productCat": "asjd",
		"price": 1246,
		"model": 2020,
		"weight": 135,
		"daysToExpire": 242,
		"popularity": "low"
	}, {
		"productName": "jhjk",
		"productCat": "kk",
		"price": 1247,
		"model": 2021,
		"weight": 136,
		"daysToExpire": 243,
		"popularity": "high"
	}, {
		"productName": "zszs",
		"productCat": "asjd",
		"price": 1248,
		"model": 2022,
		"weight": 137,
		"daysToExpire": 244,
		"popularity": "high"
	}, {
		"productName": "kkk",
		"productCat": "asjd",
		"price": 1249,
		"model": 2023,
		"weight": 138,
		"daysToExpire": 245,
		"popularity": "low"
	}, {
		"productName": "rrr",
		"productCat": "kk",
		"price": 1250,
		"model": 2024,
		"weight": 139,
		"daysToExpire": 246,
		"popularity": "high"
	}, {
		"productName": "rdtr",
		"productCat": "asjd",
		"price": 1251,
		"model": 2025,
		"weight": 140,
		"daysToExpire": 247,
		"popularity": "high"
	}];
